services:
  db:
    container_name: db-mySql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: FideliPlus
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - ./db:/var/lib/mysql
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80 # map host port 8081 to container port 80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306